// <auto-generated />
using System;
using CoinUpWorkerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinUpWorkerService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127085813_RankInCoinsMarket")]
    partial class RankInCoinsMarket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoinUpWorkerService.Models.CoinsMarket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Ath")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ath_Change_Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Ath_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Atl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Atl_Change_Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Atl_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Circulating_Supply")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Current_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Fully_Diluted_Valuation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("High_24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Last_Updated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Low_24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Market_Cap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Market_Cap_Change_24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Market_Cap_Change_Percentage_24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Market_Cap_Rank")
                        .HasColumnType("int");

                    b.Property<decimal?>("Max_Supply")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price_Change_24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price_Change_Percentage_24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Total_Supply")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CoinsMarket");
                });

            modelBuilder.Entity("CoinUpWorkerService.Models.CoinsMarketCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MarketCap")
                        .HasColumnType("float");

                    b.Property<double>("MarketCapChange24h")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Top3Coins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Top3CoinsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Volume24h")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CoinsMarketCategory");
                });

            modelBuilder.Entity("CoinUpWorkerService.Models.MarketChartDetails", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MarketCapsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PricesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalVolumesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarketChartDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
